import type { INodeProperties } from 'n8n-workflow';
import { attendeeUuidField, eventUuidField, paginationFields } from '../../shared/fields';

const allOperations = [
	'getAll',
	'get',
	'getCheckIn',
	'getCheckpointCheckIns',
	'getWorkshopCheckIns',
	'create',
	'update',
	'confirm',
	'reject',
	'resendEmail',
];
const showForGetAll = { resource: ['attendee'], operation: ['getAll'] };

export const attendeeFields: INodeProperties[] = [
	eventUuidField({ resource: ['attendee'], operation: allOperations }),
	// Every operation but Create addresses an existing attendee.
	attendeeUuidField({
		resource: ['attendee'],
		operation: allOperations.filter((operation) => !['getAll', 'create'].includes(operation)),
	}),
	...paginationFields({
		resource: ['attendee'],
		operation: ['getAll', 'getCheckpointCheckIns', 'getWorkshopCheckIns'],
	}),
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: showForGetAll },
		options: [
			{
				displayName: 'Attendee Type IDs',
				name: 'attendee_types',
				type: 'string',
				default: '',
				placeholder: '100,101',
				description: 'Comma-separated list of attendee type IDs',
				routing: { send: { type: 'query', property: 'attendee_types' } },
			},
			{
				displayName: 'Company',
				name: 'company',
				type: 'string',
				default: '',
				description: 'Partial match on the company',
				routing: { send: { type: 'query', property: 'company' } },
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				description: 'Partial match on the email',
				routing: { send: { type: 'query', property: 'email' } },
			},
			{
				displayName: 'First Name',
				name: 'first_name',
				type: 'string',
				default: '',
				description: 'Partial match on the first name',
				routing: { send: { type: 'query', property: 'first_name' } },
			},
			{
				displayName: 'IDs',
				name: 'ids',
				type: 'string',
				default: '',
				placeholder: '5001,5002',
				description: 'Comma-separated list of attendee IDs',
				routing: { send: { type: 'query', property: 'ids' } },
			},
			{
				displayName: 'Include Archived',
				name: 'include_archived',
				type: 'boolean',
				default: false,
				description: 'Whether to include archived attendees',
				routing: { send: { type: 'query', property: 'include_archived' } },
			},
			{
				displayName: 'Include Rejected',
				name: 'include_rejected',
				type: 'boolean',
				default: false,
				description: 'Whether to include rejected attendees',
				routing: { send: { type: 'query', property: 'include_rejected' } },
			},
			{
				displayName: 'Last Name',
				name: 'last_name',
				type: 'string',
				default: '',
				description: 'Partial match on the last name',
				routing: { send: { type: 'query', property: 'last_name' } },
			},
			{
				displayName: 'Only Checked In',
				name: 'only_checked_in',
				type: 'boolean',
				default: false,
				description: 'Whether to return only checked-in attendees',
				routing: { send: { type: 'query', property: 'only_checked_in' } },
			},
			{
				displayName: 'Only Confirmed',
				name: 'only_confirmed',
				type: 'boolean',
				default: false,
				description: 'Whether to return only confirmed attendees',
				routing: { send: { type: 'query', property: 'only_confirmed' } },
			},
			{
				displayName: 'Only Unchecked In',
				name: 'only_unchecked_in',
				type: 'boolean',
				default: false,
				description: 'Whether to return only attendees who have not checked in',
				routing: { send: { type: 'query', property: 'only_unchecked_in' } },
			},
			{
				displayName: 'Order',
				name: 'order',
				type: 'string',
				default: '',
				placeholder: 'created_at desc',
				description: 'Sort order as "column direction". Up to two fields, comma-separated.',
				routing: { send: { type: 'query', property: 'order' } },
			},
			{
				displayName: 'Paid',
				name: 'paid',
				type: 'boolean',
				default: true,
				description: 'Whether to return only paid (true) or only unpaid (false) attendees',
				routing: { send: { type: 'query', property: 'paid' } },
			},
		],
	},
];
