import type { INodeProperties } from 'n8n-workflow';
import { eventUuidField, optionalFields, paginationFields } from '../../shared/fields';

const showOnlyForAttendeeTypes = { resource: ['attendeeType'] };
const showForCreate = { resource: ['attendeeType'], operation: ['create'] };
const showForUpdate = { resource: ['attendeeType'], operation: ['update'] };
const showForCustomFields = {
	resource: ['attendeeType'],
	operation: ['createCustomField', 'updateCustomField'],
};

const CHOICE_INPUTS = ['select', 'checkbox', 'radio'];
const TEXT_INPUTS = ['text_field', 'text_area'];

const nameField: INodeProperties = {
	displayName: 'Name',
	name: 'name',
	type: 'string',
	default: '',
	description: 'The name of the attendee type',
	routing: { send: { type: 'body', property: 'name' } },
};

const limitField: INodeProperties = {
	displayName: 'Seat Limit',
	name: 'seat_limit',
	type: 'number',
	default: 0,
	typeOptions: { minValue: 0 },
	description: 'How many attendees may register under this type. 0 means unlimited.',
	routing: { send: { type: 'body', property: 'limit' } },
};

/** Optional on both create and update. */
const sharedFields: INodeProperties[] = [
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		description: 'What this attendee type is for',
		routing: { send: { type: 'body', property: 'description' } },
	},
	{
		displayName: 'Price',
		name: 'price',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, numberPrecision: 2 },
		description: 'What registering under this type costs, in the currency of the event',
		routing: { send: { type: 'body', property: 'price' } },
	},
	{
		displayName: 'Attendance Mode',
		name: 'attendance_mode',
		type: 'options',
		default: 'offline',
		options: [
			{ name: 'Mixed', value: 'mixed' },
			{ name: 'Offline', value: 'offline' },
			{ name: 'Online', value: 'online' },
		],
		description: 'How attendees of this type attend the event',
		routing: { send: { type: 'body', property: 'attendance_mode' } },
	},
	{
		displayName: 'Allow Public Registration',
		name: 'allow_public_registration',
		type: 'boolean',
		default: true,
		description: 'Whether people can pick this type on the public registration form',
		routing: { send: { type: 'body', property: 'allow_public_registration' } },
	},
	{
		displayName: 'Confirmation Required',
		name: 'confirmation_required',
		type: 'boolean',
		default: false,
		description: 'Whether registrations of this type need an admin to confirm them',
		routing: { send: { type: 'body', property: 'confirmation_required' } },
	},
	{
		displayName: 'Min Selected Workshops',
		name: 'min_selected_workshops',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Fewest workshops an attendee of this type must book',
		routing: { send: { type: 'body', property: 'min_selected_workshops' } },
	},
	{
		displayName: 'Max Selected Workshops',
		name: 'max_selected_workshops',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Most workshops an attendee of this type may book',
		routing: { send: { type: 'body', property: 'max_selected_workshops' } },
	},
];

/**
 * Which of these matter depends on the input type, so each one is gated on it. The `/`
 * prefix is what makes displayOptions read `inputType` from the node root rather than
 * from inside this collection.
 */
const customFieldOptions: INodeProperties[] = [
	{
		displayName: 'Required',
		name: 'required',
		type: 'boolean',
		default: false,
		description: 'Whether the attendee must fill the field in',
		routing: { send: { type: 'body', property: 'required' } },
	},
	{
		displayName: 'Display',
		name: 'display',
		type: 'boolean',
		default: true,
		description: 'Whether the field is shown on the registration form',
		routing: { send: { type: 'body', property: 'display' } },
	},
	{
		displayName: 'Edit Admin Only',
		name: 'edit_admin_only',
		type: 'boolean',
		default: false,
		description: 'Whether only admins may edit the field',
		routing: { send: { type: 'body', property: 'edit_admin_only' } },
	},
	{
		displayName: 'Available in Public Listings',
		name: 'available_public_listings',
		type: 'boolean',
		default: false,
		description: 'Whether the value appears in public attendee listings',
		routing: { send: { type: 'body', property: 'available_public_listings' } },
	},
	{
		displayName: 'Internal ID',
		name: 'internal_id',
		type: 'string',
		default: '',
		placeholder: 'tshirt-size',
		description: 'Stable key of your own for the field. Letters, digits and hyphens only.',
		routing: { send: { type: 'body', property: 'internal_id' } },
	},
	{
		displayName: 'Allow Duplicate Values',
		name: 'allow_duplicate_values',
		type: 'boolean',
		default: true,
		description: 'Whether two attendees may pick the same value',
		displayOptions: { show: { '/inputType': CHOICE_INPUTS } },
		routing: { send: { type: 'body', property: 'allow_duplicate_values' } },
	},
	{
		displayName: 'Filterable',
		name: 'filterable',
		type: 'boolean',
		default: false,
		description: 'Whether the field can be used as a filter in the admin',
		displayOptions: { show: { '/inputType': CHOICE_INPUTS } },
		routing: { send: { type: 'body', property: 'filterable' } },
	},
	{
		displayName: 'Min Selected Options',
		name: 'min_selected_options',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Fewest choices the attendee must select',
		displayOptions: { show: { '/inputType': CHOICE_INPUTS } },
		routing: { send: { type: 'body', property: 'min_selected_options' } },
	},
	{
		displayName: 'Max Selected Options',
		name: 'max_selected_options',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Most choices the attendee may select',
		displayOptions: { show: { '/inputType': CHOICE_INPUTS } },
		routing: { send: { type: 'body', property: 'max_selected_options' } },
	},
	{
		displayName: 'Render as Select Tag',
		name: 'use_select_tag',
		type: 'boolean',
		default: false,
		description: 'Whether to render the checkbox as a select tag',
		displayOptions: { show: { '/inputType': ['checkbox'] } },
		routing: { send: { type: 'body', property: 'use_select_tag' } },
	},
	{
		displayName: 'Render as Radio Buttons',
		name: 'use_radio_buttons',
		type: 'boolean',
		default: false,
		description: 'Whether to render the select as radio buttons',
		displayOptions: { show: { '/inputType': ['select'] } },
		routing: { send: { type: 'body', property: 'use_radio_buttons' } },
	},
	{
		displayName: 'Max Chars',
		name: 'max_chars',
		type: 'number',
		default: 255,
		typeOptions: { minValue: 1 },
		description: 'Longest value the attendee may type',
		displayOptions: { show: { '/inputType': TEXT_INPUTS } },
		routing: { send: { type: 'body', property: 'max_chars' } },
	},
	{
		displayName: 'Show When Checked In',
		name: 'show_when_checked_in',
		type: 'boolean',
		default: false,
		description: 'Whether the field is shown to attendees who have checked in',
		displayOptions: { show: { '/inputType': TEXT_INPUTS } },
		routing: { send: { type: 'body', property: 'show_when_checked_in' } },
	},
	{
		displayName: 'Format Validator',
		name: 'format_validator',
		type: 'options',
		default: 2,
		options: [
			{ name: 'Age Limited', value: 6 },
			{ name: 'Alphabetic', value: 3 },
			{ name: 'Chilean Tax ID', value: 5 },
			{ name: 'Numeric', value: 2 },
			{ name: 'Telephone', value: 4 },
			{ name: 'Value Limited', value: 1 },
		],
		description: 'Which format the typed value must match',
		displayOptions: { show: { '/inputType': ['text_field'] } },
		routing: { send: { type: 'body', property: 'format_validator' } },
	},
	{
		displayName: 'Limit Value Range',
		name: 'value_limited',
		type: 'boolean',
		default: false,
		description: 'Whether to restrict the value to the Lower Bound and Upper Bound range',
		displayOptions: { show: { '/inputType': ['text_field'] } },
		// The API models this as 0/1 rather than a boolean.
		routing: {
			send: { type: 'body', property: 'value_limited', value: '={{ $value ? 1 : 0 }}' },
		},
	},
	{
		displayName: 'Lower Bound',
		name: 'lower_bound',
		type: 'string',
		default: '',
		description: 'Smallest accepted number, or earliest accepted date',
		displayOptions: { show: { '/inputType': ['text_field', 'datetime'] } },
		routing: { send: { type: 'body', property: 'lower_bound' } },
	},
	{
		displayName: 'Upper Bound',
		name: 'upper_bound',
		type: 'string',
		default: '',
		description: 'Largest accepted number, or latest accepted date',
		displayOptions: { show: { '/inputType': ['text_field', 'datetime'] } },
		routing: { send: { type: 'body', property: 'upper_bound' } },
	},
	{
		displayName: 'Include Time',
		name: 'include_time',
		type: 'boolean',
		default: false,
		description: 'Whether the picker asks for a time as well as a date',
		displayOptions: { show: { '/inputType': ['datetime'] } },
		routing: { send: { type: 'body', property: 'include_time' } },
	},
	{
		displayName: 'Min Age',
		name: 'min_age',
		type: 'number',
		default: 18,
		typeOptions: { minValue: 0 },
		description: 'Youngest age accepted. Only meaningful on the built-in birthdate field.',
		displayOptions: { show: { '/inputType': ['datetime'] } },
		routing: { send: { type: 'body', property: 'min_age' } },
	},
	{
		displayName: 'Use as Header',
		name: 'use_as_header',
		type: 'boolean',
		default: false,
		description: 'Whether the label is rendered as a section header',
		displayOptions: { show: { '/inputType': ['label'] } },
		routing: { send: { type: 'body', property: 'use_as_header' } },
	},
];

export const attendeeTypeFields: INodeProperties[] = [
	eventUuidField(showOnlyForAttendeeTypes),
	{
		displayName: 'Attendee Type ID',
		name: 'attendeeTypeId',
		type: 'string',
		required: true,
		default: '',
		placeholder: '100',
		displayOptions: {
			show: {
				resource: ['attendeeType'],
				operation: [
					'get',
					'getFormSchema',
					'getCustomFields',
					'getGroupLimits',
					'update',
					'createCustomField',
					'updateCustomField',
				],
			},
		},
		description: 'The numeric ID of the attendee type',
	},
	{ ...nameField, name: 'attendeeTypeName', required: true, displayOptions: { show: showForCreate } },
	{ ...limitField, name: 'seatLimit', required: true, displayOptions: { show: showForCreate } },
	optionalFields({
		name: 'attendeeTypeAdditionalFields',
		displayName: 'Additional Fields',
		show: showForCreate,
		options: sharedFields,
	}),
	optionalFields({
		name: 'attendeeTypeUpdateFields',
		displayName: 'Update Fields',
		show: showForUpdate,
		options: [...sharedFields, nameField, limitField],
	}),
	{
		displayName: 'Custom Field ID',
		name: 'customFieldId',
		type: 'string',
		required: true,
		default: '',
		placeholder: '4521',
		displayOptions: {
			show: { resource: ['attendeeType'], operation: ['updateCustomField'] },
		},
		description:
			'The numeric ID of the custom field, as returned by Get Many Custom Fields',
	},
	{
		displayName: 'Custom Field Name',
		name: 'customFieldName',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'T-shirt size',
		displayOptions: { show: showForCustomFields },
		description: 'The label shown above the field on the registration form',
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Input Type',
		name: 'inputType',
		type: 'options',
		required: true,
		default: 'text_field',
		options: [
			{ name: 'Checkbox', value: 'checkbox' },
			{ name: 'City', value: 'city' },
			{ name: 'Country', value: 'country' },
			{ name: 'Datetime', value: 'datetime' },
			{ name: 'File', value: 'file' },
			{ name: 'Image File', value: 'image_file' },
			{ name: 'Label', value: 'label' },
			{ name: 'Radio', value: 'radio' },
			{ name: 'Select', value: 'select' },
			{ name: 'Terms and Conditions', value: 'terms_conditions' },
			{ name: 'Text Area', value: 'text_area' },
			{ name: 'Text Field', value: 'text_field' },
		],
		displayOptions: { show: showForCustomFields },
		description: 'Which control the attendee sees. It also decides which options below apply.',
		routing: { send: { type: 'body', property: 'input_type' } },
	},
	{
		displayName: 'Values',
		name: 'customFieldValues',
		type: 'string',
		typeOptions: { multipleValues: true },
		default: [],
		placeholder: 'S',
		displayOptions: {
			show: { resource: ['attendeeType'], operation: ['createCustomField', 'updateCustomField'], inputType: CHOICE_INPUTS },
		},
		description: 'The choices offered to the attendee. Commas inside a choice are not supported.',
		routing: { send: { type: 'body', property: 'values' } },
	},
	{
		displayName: 'Terms URL',
		name: 'termsUrl',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/terms',
		displayOptions: {
			show: { resource: ['attendeeType'], operation: ['createCustomField', 'updateCustomField'], inputType: ['terms_conditions'] },
		},
		description: 'Where the terms live. Uploading a file is not supported through the API.',
		routing: { send: { type: 'body', property: 'terms_url' } },
	},
	optionalFields({
		name: 'customFieldOptions',
		displayName: 'Options',
		show: showForCustomFields,
		options: customFieldOptions,
	}),
	...paginationFields({
		resource: ['attendeeType'],
		operation: ['getAll', 'getCustomFields', 'getGroupLimits'],
	}),
];
